[package]
name = "week9"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.12.0"
actix-web = "4.0.0-beta.14"
actix-web-actors = "4.0.0-beta.13"
tungstenite = "0.15.0"
futures = "0.3"